global:
  scrape_interval: 15s # How often to scrape targets by default.

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464'] # OpenTelemetry Collector scrape endpoint